### ISSUE TITLE
Have you tested GIM methods?

### ISSUE THREAD

**Issue by noone-code** [VictorZoo/LoD-Loc#1]
According to the results published by [GIM](https://github.com/xuelunshen/gim#-zeb-zero-shot-evaluation-benchmark), the GIM trained model has good generalization performance. The currently published $GIM_{DKM}$ has the best performance (better than RoMA). I am curious if you have tested GIM's model?

**Comment by VictorZoo** [comment]
Hi， we are currently occupied with other projects and have not tested this new method.

**Comment by noone-code** [comment]
I am very curious about the performance of this latest and strongest method. It should demonstrate and push the performance limit of methods in this field. I look forward to you testing and comparing it to showcase the advantages of Lod-Loc.
