### ISSUE TITLE
datatset

### ISSUE THREAD

**Issue by chl916185** [VictorZoo/LoD-Loc#3]
@VictorZoo 
The data download link is invalid, can you update the new address?

**Comment by VictorZoo** [comment]
Hi, the previous link is accidentally broken, we update the new share address.

**Comment by curious-energy** [comment]
Thanks for your contribution, I checked the data download link and it has not been fixed yet.

![image](https://github.com/user-attachments/assets/8a0bc641-83c0-433d-a2cf-47d9aa297946)

**Comment by VictorZoo** [comment]
> Thanks for your contribution, I checked the data download link and it has not been fixed yet.
> 
> ![image](https://private-user-images.githubusercontent.com/28819684/378869324-8a0bc641-83c0-433d-a2cf-47d9aa297946.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NjQ1MDgsIm5iZiI6MTcyOTY2NDIwOCwicGF0aCI6Ii8yODgxOTY4NC8zNzg4NjkzMjQtOGEwYmM2NDEtODNjMC00MzNkLWEyY2YtNDdkOWFhMjk3OTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDA2MTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNTE1MTZhZDljYjViZDBmNmU1MjM2OTdkODNlZjhiMWE3ZWJmZWFkNzM1NjZiODg1MDcwY2YzZmY5ZTE0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CfyNY3H-qcIATaPmmvK7Ns7wJWpevP6XPk7V_zT0Ajg)

Updated
