### ISSUE TITLE
The data set link is invalid ~ the shared file has been cancelled.

### ISSUE THREAD

**Issue by lidapengpeng** [VictorZoo/LoD-Loc#6]
The data set link shared on Baidu Netdisk has been cancelled. Can the link be updated again? Thanks
![image](https://github.com/user-attachments/assets/395faa3c-9ed0-45ba-bc74-57bbe9c98010)

**Comment by VictorZoo** [comment]
Hi @lidapengpeng , the link has been updated, please check it.
