### ISSUE TITLE
.exr

### ISSUE THREAD

**Issue by Boldgirl** [VictorZoo/LoD-Loc#7]
hello!when I execute python ./script/data_proccess.py  --config_file=./config/Swiss_preprocess.json   
the problem is:
[ WARN:0@331.178] global loadsave.cpp:241 findDecoder imread_('dataset/Swiss-EPFL/inPlace/depth/urbanscape-2020-11-11-planned_00593_100_0808_0406_img0001.exr'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "./script/data_proccess.py", line 228, in <module>
    main(config)
  File "./script/data_proccess.py", line 214, in main
    wireframe_extract(points3D_all, wireframe_points_save_pth, depth_dir, str(GPS_pth).split('.')[0], intri_pth, q_img_pth, config["if_save"])
  File "/home/fhy_yy_01/LoD-Loc-main/script/utils.py", line 384, in wireframe_extract
    depth = read_depth(depth_pth)
  File "/home/fhy_yy_01/LoD-Loc-main/script/utils.py", line 290, in read_depth
    depth = torch.tensor(depth)
RuntimeError: Could not infer dtype of NoneType

I'd like to ask:Why didn't this process generate a file named "urbanscape-2020-11-11-planned_00593_100_0808_0406_img0001.exr",but it generate 00001.exr  

Can you help me?Thank you

**Comment by VictorZoo** [comment]
Hi @Boldgirl ,

We have noticed that the file extension of "0001.exr" may automatically change depending on the computer or software environment. Please check and rename the file accordingly to ensure proper usage.

**Comment by ZhouMengjie** [comment]
Hi, I also met the same problem. when i am trying to render depth maps for "UAVD4L-LoD"-"InTraj", i got "0002.exr" "D0002.exr", "DJ0002.exr". It seems that the correct file name should be like this "DJI_20231207173403_0141_W0002.exr". Could I know whether this is relevant with blender version? I use blender-4.3.0-linux-x64 while you are using a lower version? I am looking forward to your help. Thank you.

**Comment by VictorZoo** [comment]
Please see #9
