### ISSUE TITLE
FileNotFoundError: GPS pose file not found: /media/lsg/data1/dataset/UAVD4L-LoD/Synthesis/GPS_pose.txt/401996@3131353@150@1@25@0.jpg

### ISSUE THREAD

**Issue by dizzyrue** [VictorZoo/LoD-Loc#8]
how to fix this issue？ thank you

**Comment by VictorZoo** [comment]
Seems to a Path problem. 'GPS_pose.txt' is a .txt file not a directory, cannot contain the '401996@3131353@150@1@25@0.jpg'. Please check the filepath.
